# Generated by Django 4.2 on 2023-05-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_lecture_options_alter_lecturefile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturefile',
            name='file',
            field=models.FileField(upload_to='materials'),
        ),
    ]
