# Generated by Django 4.2 on 2023-04-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationregistration',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
