# Generated by Django 4.2 on 2023-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_university_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='universities'),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
