# Generated by Django 4.2 on 2023-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_university_avatar_university_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='universities'),
        ),
    ]
