# Generated by Django 4.2 on 2023-04-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
