# Generated by Django 4.2 on 2023-05-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_delete_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='avatar',
            field=models.ImageField(default='universities/default.jpg', upload_to='universities'),
        ),
    ]
