# Generated by Django 4.2 on 2023-05-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
