# Generated by Django 4.2 on 2023-04-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_rating_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
