# Generated by Django 4.2 on 2023-04-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_comment_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(default='islamchik', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.tags'),
        ),
    ]
