# Generated by Django 4.2 on 2023-04-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_tags_alter_article_options_remove_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='articles/default.jpg', upload_to='articles'),
        ),
    ]
