# Generated by Django 4.2 on 2023-04-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/default.jpg', upload_to='news'),
        ),
    ]
